### ISSUE TITLE
Blog post for Python-MoA

### ISSUE THREAD

**Issue by dcharbon** [Quansight-Labs/python-moa#14]

**Comment by costrouc** [comment]
Working on today.

**Comment by costrouc** [comment]
Initial post https://github.com/Quansight-Labs/python-moa/blob/master/docs/introduction.rst need to create an equivalent notebook.

**Comment by rgommers** [comment]
@costrouc if it's easier, you can also just run the `.rst` through Pandoc and get Markdown out. Pygments highlighting works, so that should require minimal fixups only. 

The Jupyter notebook support I have working, but it's still a bit ugly (Jupyter has a known issue with embedding and its CSS clashing with the main CSS of the site - still need to fix that up).

**Comment by rgommers** [comment]
Nice blog post by the way, reads well.

**Comment by costrouc** [comment]
Thanks @rgommers! I will have a jupyter notebook for you today of the equivalent post. Should I open a PR in https://github.com/Quansight-Labs/quansight-labs-site to add it?

**Comment by rgommers** [comment]
Yes, a PR to that repo would be great.

**Comment by costrouc** [comment]
See PR https://github.com/Quansight-Labs/quansight-labs-site/pull/5

**Comment by costrouc** [comment]
Closing as blog was recently added! https://labs.quansight.org/blog/2019/04/python-moa-tensor-compiler/
